const VIEWS={battlepass:["SEASON 1","배틀패스"],documents:["COMMUNITY MAP","문서 위치"],quests:["KORD BREACH","시즌 퀘스트"],allergy:["PERSONAL MODIFIER","알러지 체크"],modifiers:["SEASON TRAITS","시즌 특성"],kappa:["COLLECTOR","카파 체크리스트"]};
const VIEW_ROUTES={battlepass:"/tarkov/season-1/battle-pass/",documents:"/tarkov/season-1/documents/",quests:"/tarkov/season-1/quests/",allergy:"/tarkov/season-1/allergy/",modifiers:"/tarkov/season-1/traits/",kappa:"/tarkov/season-1/kappa/"};
const PAGE_VIEW=document.body.dataset.view&&VIEWS[document.body.dataset.view]?document.body.dataset.view:"battlepass";
const KEYS={view:"tarkov-hub:view:v1",allergy:"tarkov-hub:allergy:v1",modifiers:"tarkov-hub:modifiers:v1",questsDone:"tarkov-hub:quests-done:v1",seasonAchievementsDone:"tarkov-hub:season-achievements-done:v1",otherAchievementsDone:"tarkov-hub:other-achievements-done:v1",kappaItems:"tarkov-hub:kappa-items:v1",kappaRequirements:"tarkov-hub:kappa-requirements:v1",language:"tarkov-tools:language:v1",map:"tarkov-hub:map:v1"};
const LANGUAGES=["ko","en","ja"];
const HUB_SEASON_END=new Date(2026,11,7);
const labelByLanguage={ko:{battlepass:"배틀패스",documents:"문서 위치",quests:"시즌 퀘스트",allergy:"알러지 체크",modifiers:"시즌 특성",kappa:"카파 체크리스트"},en:{battlepass:"Battle Pass",documents:"Document Map",quests:"Season Quests",allergy:"Allergy Check",modifiers:"Season Traits",kappa:"Kappa Checklist"},ja:{battlepass:"バトルパス",documents:"文書マップ",quests:"シーズンクエスト",allergy:"アレルギーチェック",modifiers:"シーズン特性",kappa:"カッパチェックリスト"}};
const HUB_MAPS=[
{id:"factory",name:{ko:"공장",en:"Factory",ja:"ファクトリー"},docs:["project","blueprints"]},{id:"customs",name:{ko:"세관",en:"Customs",ja:"カスタム"},docs:["financial","project"]},{id:"reserve",name:{ko:"리저브",en:"Reserve",ja:"リザーブ"},docs:["pmc","project"]},{id:"interchange",name:{ko:"인터체인지",en:"Interchange",ja:"インターチェンジ"},docs:["financial","blueprints"]},{id:"woods",name:{ko:"삼림",en:"Woods",ja:"ウッズ"},docs:["test","technical"]},{id:"shoreline",name:{ko:"해안선",en:"Shoreline",ja:"ショアライン"},docs:["test","technical"]},{id:"lighthouse",name:{ko:"등대",en:"Lighthouse",ja:"ライトハウス"},docs:["pmc","technical"]},{id:"icebreaker",name:{ko:"쇄빙선",en:"Icebreaker",ja:"アイスブレーカー"},docs:["pmc","test"]},{id:"streets",name:{ko:"타르코프 시내",en:"Streets",ja:"ストリート"},docs:["financial","user"]},{id:"ground-zero",name:{ko:"그라운드 제로",en:"Ground Zero",ja:"グラウンドゼロ"},docs:["user","medical"]},{id:"laboratory",name:{ko:"연구소",en:"The Lab",ja:"ラボ"},docs:["user","medical"]},{id:"labyrinth",name:{ko:"미궁",en:"Labyrinth",ja:"ラビリンス"},docs:["blueprints","medical"]}
];
const HUB_DOCUMENT_ICONS={financial:"accounting.webp",pmc:"pmc-personnel.webp",project:"project.webp",blueprints:"blueprints-technical.webp",test:"test.webp",user:"user.webp",medical:"medical.webp",technical:"equipment.webp"};
const UI={
ko:{questTitle:"시즌 퀘스트 진행 순서",questDesc:"메인 퀘스트 14개와 서브 퀘스트 2개를 현재 확인되는 순서대로 정리했습니다.",totalQuests:"전체 퀘스트",allergyTitle:"알러지 특성 체크리스트",allergyDesc:"사용 후 증상이 발생한 아이템은 알러지, 이상이 없었던 아이템은 안전으로 기록하세요. 상태는 자동 저장됩니다.",allergic:"알러지",safe:"안전",safeChecked:"안전 확인",totalCandidates:"전체 후보",all:"전체",search:"아이템 이름 검색",reset:"전체 초기화",noResults:"검색 결과가 없습니다.",modifierTitle:"시즌 특성(모디파이어) 시뮬레이터",modifierDesc:"부정 특성(+)으로 포인트를 벌고 긍정 특성(−)을 선택하세요. 잔여 포인트가 0 이상이면 적용 가능한 조합입니다.",points:"잔여 포인트",selected:"선택",result:"판정",shortage:"부족",random:"랜덤 조합",none:"선택한 특성이 없습니다.",negative:"부정 특성 · 디버프",positive:"긍정 특성 · 보너스",global:"글로벌 모디파이어",globalNote:"항상 적용 · 비용 없음",blocked:"동시 선택 불가",count:"개",confirmReset:"알러지 체크 기록을 모두 초기화할까요?",groups:["음료","식품","진통제 · 의약품","자극제 · 주사기"]},
en:{questTitle:"Season Quest Order",questDesc:"The 14 main quests and 2 side quests are listed in the currently known order.",totalQuests:"Total quests",allergyTitle:"Allergy Trait Checklist",allergyDesc:"Mark items that cause symptoms as allergic and items without symptoms as safe. Your progress is saved automatically.",allergic:"Allergic",safe:"Safe",safeChecked:"Safe",totalCandidates:"Candidates",all:"All",search:"Search items",reset:"Reset all",noResults:"No results found.",modifierTitle:"Season Trait (Modifier) Simulator",modifierDesc:"Earn points with negative traits (+), then spend them on positive traits (−). A build is valid when the remaining points are zero or higher.",points:"Points left",selected:"Selected",result:"Result",shortage:"SHORT",random:"Random build",none:"No modifiers selected.",negative:"Negative traits · Debuffs",positive:"Positive traits · Bonuses",global:"Global Modifiers",globalNote:"Always active · no cost",blocked:"Cannot combine",count:"",confirmReset:"Reset all allergy records?",groups:["Drinks","Food","Painkillers · Medicine","Stimulants · Injectors"]},
ja:{questTitle:"シーズンクエスト進行順",questDesc:"メインクエスト14件とサブクエスト2件を現在確認されている順番で整理しました。",totalQuests:"全クエスト",allergyTitle:"アレルギー特性チェックリスト",allergyDesc:"症状が出たアイテムはアレルギー、問題がなかったアイテムは安全として記録できます。状態は自動保存されます。",allergic:"アレルギー",safe:"安全",safeChecked:"安全確認",totalCandidates:"候補数",all:"すべて",search:"アイテム検索",reset:"すべてリセット",noResults:"検索結果がありません。",modifierTitle:"シーズン特性（モディファイア）シミュレーター",modifierDesc:"マイナス特性（＋）でポイントを獲得し、プラス特性（−）を選択します。残りポイントが0以上なら有効です。",points:"残りポイント",selected:"選択",result:"判定",shortage:"不足",random:"ランダム構成",none:"特性が選択されていません。",negative:"マイナス特性 · デバフ",positive:"プラス特性 · ボーナス",global:"グローバルモディファイア",globalNote:"常に適用 · コストなし",blocked:"同時選択不可",count:"個",confirmReset:"アレルギー記録をすべてリセットしますか？",groups:["飲料","食品","鎮痛剤 · 医薬品","刺激剤 · 注射器"]}
};
UI.ko.questDesc="메인 퀘스트 13개와 서브 퀘스트 3개를 현재 확인되는 순서대로 정리했습니다.";
UI.en.questDesc="The 13 main quests and 3 side quests are listed in the currently known order.";
UI.ja.questDesc="メインクエスト13件とサブクエスト3件を現在確認されている順番で整理しました。";
const KAPPA_UI={
ko:{title:"카파 컨테이너 체크리스트",desc:"Collector 해금 조건과 관련 퀘스트, 인레이드 획득이 필요한 아이템을 한곳에서 확인하세요. 체크 상태는 자동 저장됩니다.",requirements:"해금 조건",quests:"관련 퀘스트",items:"카파 아이템",done:"완료",remaining:"남음",found:"획득 완료",reset:"전체 초기화",confirmReset:"카파 체크 기록을 모두 초기화할까요?",source:"Collector 위키에서 최신 조건 확인",imageSource:"아이템 이미지 제공: tarkov.dev",fir:"모든 아이템은 인레이드(Found in Raid) 상태로 제출해야 합니다."},
en:{title:"Kappa Container Checklist",desc:"Track Collector unlock requirements, related quests, and every item that must be found in raid. Your progress is saved automatically.",requirements:"Unlock requirements",quests:"Related quests",items:"Kappa items",done:"Completed",remaining:"Remaining",found:"Found",reset:"Reset all",confirmReset:"Reset all Kappa checklist progress?",source:"Check the latest requirements on the Collector Wiki",imageSource:"Item images provided by tarkov.dev",fir:"Every item must be handed over with Found in Raid status."},
ja:{title:"カッパコンテナ・チェックリスト",desc:"Collectorの解放条件、関連クエスト、レイド内で入手する必要があるアイテムをまとめて確認できます。進行状況は自動保存されます。",requirements:"解放条件",quests:"関連クエスト",items:"カッパアイテム",done:"完了",remaining:"残り",found:"入手済み",reset:"すべてリセット",confirmReset:"カッパのチェック記録をすべてリセットしますか？",source:"Collector Wikiで最新条件を確認",imageSource:"アイテム画像提供: tarkov.dev",fir:"すべてのアイテムはFound in Raid状態で引き渡す必要があります。"}
};
const KAPPA_REQUIREMENTS=[
{id:"level-40",type:"condition",ko:"캐릭터 레벨 40 달성",en:"Reach character level 40",ja:"キャラクターレベル40に到達"},
{id:"fence-rep-3",type:"condition",ko:"펜스 평판 3.0 이상 달성",en:"Reach Fence reputation 3.0 or higher",ja:"Fenceの評判を3.0以上にする",portrait:"https://assets.tarkov.dev/579dc571d53a0658a154fbec.webp"},
{id:"trader-prapor-ll4",type:"condition",ko:"프라퍼 우호도 4 달성",en:"Reach Loyalty Level 4 with Prapor",ja:"Praporの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/54cb50c76803fa8b248b4571.webp"},
{id:"trader-therapist-ll4",type:"condition",ko:"테라피스트 우호도 4 달성",en:"Reach Loyalty Level 4 with Therapist",ja:"Therapistの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/54cb57776803fa99248b456e.webp"},
{id:"trader-skier-ll4",type:"condition",ko:"스키어 우호도 4 달성",en:"Reach Loyalty Level 4 with Skier",ja:"Skierの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/58330581ace78e27b8b10cee.webp"},
{id:"trader-peacekeeper-ll4",type:"condition",ko:"피스키퍼 우호도 4 달성",en:"Reach Loyalty Level 4 with Peacekeeper",ja:"Peacekeeperの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/5935c25fb3acc3127c3d8cd9.webp"},
{id:"trader-mechanic-ll4",type:"condition",ko:"메카닉 우호도 4 달성",en:"Reach Loyalty Level 4 with Mechanic",ja:"Mechanicの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/5a7c2eca46aef81a7ca2145d.webp"},
{id:"trader-ragman-ll4",type:"condition",ko:"라그맨 우호도 4 달성",en:"Reach Loyalty Level 4 with Ragman",ja:"Ragmanの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/5ac3b934156ae10c4430e83c.webp"},
{id:"trader-jaeger-ll4",type:"condition",ko:"예거 우호도 4 달성",en:"Reach Loyalty Level 4 with Jaeger",ja:"Jaegerの信頼度レベル4に到達",portrait:"https://assets.tarkov.dev/5c0647fdd443bc2504c2d371.webp"},
{id:"chemical-3",type:"quest",ko:"Chemical - Part 3 완료",en:"Complete Chemical - Part 3",ja:"Chemical - Part 3を完了",wiki:"Chemical_-_Part_3"},
{id:"sew-it-good-2",type:"quest",ko:"Sew it Good - Part 2 완료",en:"Complete Sew it Good - Part 2",ja:"Sew_it_Good_-_Part_2を完了",wiki:"Sew_it_Good_-_Part_2"},
{id:"shooter-born",type:"quest",ko:"Shooter Born in Heaven 완료",en:"Complete Shooter Born in Heaven",ja:"Shooter Born in Heavenを完了",wiki:"Shooter_Born_in_Heaven"},
{id:"tarkov-shooter-4",type:"quest",ko:"The Tarkov Shooter - Part 4 완료",en:"Complete The Tarkov Shooter - Part 4",ja:"The Tarkov Shooter - Part 4を完了",wiki:"The_Tarkov_Shooter_-_Part_4"}
];
const KAPPA_ITEMS=`#FireKlean gun lube|5bc9b355d4351e6d1509862a;42 Signature Blend English Tea|5bc9be8fd4351e00334cae6e;Antique axe|5bc9c1e2d4351e00367fbcf0;Axel parrot figurine|62a091170b9d3c46de5b6cf2;Baddie's red beard|62a09dd4621468534a797ac7;BakeEzy cook book|62a09e73af34e73a266d932a;Battered antique book|5bc9c049d4351e44f824d360;BEAR Buddy plush toy|62a08f4c4f842e1bd12d9d62;Bottle of YMXC water|6a3557f841667bc4bb00fea4;Can of Dr. Lupo's coffee beans|5e54f6af86f7742199090bf3;Can of GigaBeef meat|6a3532423ec9d7082a05d430;Can of RatCola soda|60b0f93284c20f0feb453da7;Deadlyslob's beard oil|5bc9b9ecd4351e3bac122519;DesmondPilak CD|69f9d547b98cc4120608692a;Domontovich ushanka hat|6937f02dfd6488bb27024839;DRD body armor|62a09d79de7ac81993580530;Dunduk floppy disk|69f9d60b5de6674f08060f2a;Fake mustache|5bd073a586f7747e6f135799;French bakery baguette|6a35322b81d315afe1018ef3;Gingy keychain|62a09d3bcf4a99369e262447;Glorious E lightweight armored mask|62a09e08de7ac81993580532;Golden 1GPhone smartphone|5bc9b720d4351e450201234b;Golden egg|62a09cfe4f842e1bd12da3e4;Inseq gas pipe wrench|66b37f114410565a8f6789e2;JohnB Liquid DNB glasses|62a09e410b9d3c46de5b6e78;LM KC-130 model aircraft|6a4ce086b5644e9f0a08d08a;Loot Lord plushie|60b0f7057897d47c5b04ab94;LVNDMARK's rat poison|60b0f561c4449e4cb624c1d7;Mazoni golden dumbbell|6937edb912d456a817083e82;Missam forklift key|62a09ec84f842e1bd12da3f2;Nut Sack balaclava|69398e94ca94fd2877039504;Pestily plague mask|5e54f79686f7744022011103;Press pass (issued for NoiceGuy)|62a09cb7a04c0c5c6e0a84f8;Raven figurine|5e54f62086f774219b0f1937;SheefGG piggy bank|69f9d319c906cd16da03b374;Shroud half-mask|5e54f76986f7740366043752;Silver Badge|5bc9bdb8d4351e003562b8a1;Smoke balaclava|5fd8d28367cb5e077335170f;Tamatthi kunai knife replica|66b37ea4c5d72b0277488439;Tigzresq splint|6937ecf8628ee476240c07cb;Veritas guitar pick|5f745ee30acaeb0d490d8c5b;Video cassette with the Cyborg Killer movie|62a09e974f842e1bd12da3f0;Viibiin sneaker|66b37eb4acff495a29492407;WZ Wallet|60b0f6c058e0b0481a09ad11`.split(";").map(entry=>{const [name,itemId]=entry.split("|");return{name,itemId,id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),icon:`https://assets.tarkov.dev/${itemId}-icon.webp`}});
let currentView=PAGE_VIEW,language=LANGUAGES.includes(localStorage.getItem(KEYS.language))?localStorage.getItem(KEYS.language):"ko",currentMap=localStorage.getItem(KEYS.map)||"factory";
const ALLERGY=[
["음료","아쿠아마리|Aquamari;슈퍼워터|Canister with purified water;크바스|Norvinsky Yadreniy Kvass;생수|Bottle of water 0.6L;비상 식수|Emergency Water Ration;페브코|Pevko Light Beer;파인애플 주스|Russian Army Pineapple Juice;그랜드 주스|Grand Juice;우유|Pack of Milk;비타 주스|Vita Juice;애플 주스|Apple Juice;맥스에너지|Max Energy Drink;핫로드|Hot Rod Energy Drink;랫콜라|RatCola Soda;아이스그린티|Ice Green Tea;타르콜라|TarCola Soda;YXMC 워터보틀|Bottle of YXMC water"],
["식품","완두콩 통조림|Can of Green Peas;오리 파테 통조림|Can of Duck Pâté;데블독 마요네즈|Jar of DevilDog Mayo;올리비에 샐러드|Olivier Salad Box;이스크라 전투식량|Iskra Ration Pack;연유 통조림|Can of Condensed Milk;MRE 전투식량|MRE Ration Pack;설탕|Pack of Sugar;스프랏 통조림|Can of Sprats;타르커 육포|Tarker Dried Meat;험프백 연어 통조림|Can of Humpback Salmon;츄쇼운카 (대)|Beef Stew Large;솔티독 소시지|Salty Dog Beef Sausage;꽁치 통조림|Can of Pacific Saury;청어 통조림|Can of Herring;츄쇼운카 (소)|Beef Stew Small;스쿼시 스프레드|Can of Squash Spread;오트플레이크|Pack of Oat Flakes;알료카 초콜릿|Alyonka Chocolate Bar;슬리커즈 초콜릿|Slickers Chocolate Bar;인스턴트 라면|Pack of Instant Noodles;호밀 크루통|Rye Croutons;문샤인|Fierce Hatchling Moonshine;군용 크래커|Army Crackers;예멜랴 호밀 크루통|Emelya Rye Croutons;댄 재키엘 위스키|Dan Jackiel Whiskey;타르콥스카야 보드카|Tarkovskaya Vodka;프렌치 베이커리 바게트|French bakery baguette;기가비프 통조림|Can of GigaBeef meat"],
["진통제 · 의약품","골든스타 밤|Golden Star Balm;모르핀 주사기|Morphine Injector;바셀린 밤|Vaseline Balm;이부프로펜|Ibuprofen Painkillers;오구멘틴|Augmentin Antibiotic Pills;아날긴|Analgin Painkillers"],
["자극제 · 주사기","2A2-(b-TG)|2A2-(b-TG) Stimulant Injector;3-(b-TG)|3-(b-TG) Stimulant Injector;아드레날린|Adrenaline Injector;AHF1-M|AHF1-M Stimulant Injector;eTG-체인지|eTG-change Regenerative Injector;L1|L1 Norepinephrine Injector;뮬 (M.U.L.E.)|M.U.L.E. Stimulant Injector;멜도닌|Meldonin Injector;옵돌보스-2|Obdolbos 2 Cocktail Injector;옵돌보스|Obdolbos Cocktail Injector;P22|P22 Product 22 Injector;페르포토란|Perfotoran Blue Blood Injector;PNB|PNB Product 16 Injector;프로피탈|Propital Regenerative Injector;SJ1|SJ1 TGLabs Combat Injector;SJ12|SJ12 TGLabs Combat Injector;SJ6|SJ6 TGLabs Combat Injector;SJ9|SJ9 TGLabs Combat Injector;트리마돌|Trimadol Stimulant Injector;xTG-12|xTG-12 Antidote Injector;자구스틴|Zagustin Hemostatic Injector"],
].map(([group,text])=>[group,text.split(";").map(item=>item.split("|"))]);
const ALLERGY_ITEM_IDS=`5c0fa877d174af02a012e1cf;5d1b33a686f7742523398398;5e8f3423fd7471236e6e3b64;5448fee04bdc2dbc018b4567;60098b1705871270cd5352a1;62a09f32621468534a797acb;544fb62a4bdc2dfb738b4568;57513f9324597720a7128161;575146b724597720a27126d5;57513fcc24597720a31c09a6;57513f07245977207e26a311;5751435d24597720a27126d1;5751496424597720a27126da;60b0f93284c20f0feb453da7;575062b524597720a31c09a1;57514643245977207f2c2d09;6a3557f841667bc4bb00fea4;57347d692459774491567cf1;69774bb0a247161ff1068335;5bc9b156d4351e00367fbce9;67586b7e49c2fa592e0d8ed9;590c5d4b86f774784e1b9c45;5734773724597737fd047c14;590c5f0d86f77413997acfab;59e3577886f774176a362503;5bc9c29cd4351e003562b8a3;65815f0e647e3d7246384e14;57347d5f245977448b40fa81;57347da92459774491567cf5;635a758bfefc88a93f021b8a;5673de654bdc2d180f8b456d;57347d9c245977448b40fa85;57347d7224597744596b4e72;57347d8724597744596b4e76;57347d90245977448f7b7f65;57505f6224597709a92585a9;544fb6cc4bdc2d34748b456e;656df4fec921ad01000481a2;57347d3d245977448f7b7f61;5d1b376e86f774252519444e;5448ff904bdc2d6f028b456e;5751487e245977207e26a315;5d403f9186f7743cac3f229b;5d40407c86f774318526545a;6a35322b81d315afe1018ef3;6a3532423ec9d7082a05d430;5751a89d24597722aa0e8db0;544fb3f34bdc2d03748b456a;5755383e24597772cb798966;5af0548586f7743a532b7e99;590c695186f7741e566b64a2;544fb37f4bdc2dee738b4567;66507eabf5ddb0818b085b68;5ed515c8d380ab312177c0fa;5c10c8fd86f7743d7d706df3;5ed515f6915ec335206e4152;5c0e534186f7747fa1419867;5ed515e03a40a50460332579;5ed51652f6c34d2cc26336a1;5ed5160a87bb8443d10680b5;637b60c3b7afa97bfc3d7001;5ed5166ad380ab312177c100;5ed515ece452db0eb56fc028;637b6251104668754b72f8f9;637b6179104668754b72f8f5;5c0e530286f7747fa1419862;5c0e531286f7747fa54205c2;637b612fb7afa97bfc3d7005;5c0e531d86f7747fa23f4d42;5fca13ca637ee0341a484f46;637b620db7afa97bfc3d7009;5fca138c2a7b221b2852a5c6;5c0e533786f7747fa23f4d47`.split(";");
const POS=[
["marathon","마라토너","MARATHON RUNNER",-3,"팔·다리 스테미나 감소 속도 20% 감소"],["safecracker","금고 털이범","SAFECRACKER",-5,"물리 열쇠 사용 시 25% 확률로 내구도 미소모"],["bushborne","수색대","BUSHBORNE",-5,"식생 이동 소음·속도 둔화 75% 감소"],["juice","주스 타임","JUICE TIME",-2,"주스 섭취 시 60초 진통 효과"],["sailor","뱃사람의 향수","SAILOR'S NOSTALGIA",-2,"생선 통조림 섭취 시 15초 체력 회복"],["youth","젊음","YOUTH",-5,"에너지 소모 20% 감소, 스테미나 증가"],["tax","보호비","STREET TAX",-1,"매주 한 번 스캐브가 보호비 상납"],["shooter","타르코프의 명사수","THE TARKOV SHOOTER",-2,"볼트액션 숙련 증가, 스킬 25 시작"],["diet","식단 조절","DIET",-2,"음식 사용 시 50% 덜 소모"],["hercules","헤라클레스","HERCULES",-5,"근력·지구력 15레벨 시작"],["sprinter","스프린터","SPRINTER",-3,"달리기 속도 5% 증가"],["thrombo","혈전성향증","THROMBOPHILIA",-2,"출혈 발생 확률 25% 감소"],["hypodipsia","저갈증","HYPODIPSIA",-2,"수분 소모 20% 감소"],["polyphagia","다식증","POLYPHAGIA",-2,"에너지 소모 20% 감소"],["bones","통뼈","STURDY BONES",-3,"골절 확률·낙하 피해 감소"],["average","평범함","AVERAGE",-12,"모든 스킬 25 시작, 추가 성장 불가"],["kappa","카파 프로토콜","KAPPA PROTOCOL",-12,"카파 보안 컨테이너 즉시 획득"],["prodigy","신동","PRODIGY",-5,"스킬 경험치 30% 증가"],["lucky","럭키","LUCKY",-1,"용기 있는 자에게 행운이 따른다"]
];
const NEG=[
["hemophilia","혈우병","HEMOPHILIA",2,"출혈 발생 확률 25% 증가"],["osteoporosis","골다공증","OSTEOPOROSIS",3,"골절 확률·낙하 피해 증가"],["exhaustion","기력 고갈","EXHAUSTION",5,"스테미나 회복·최대치 감소"],["hurt","아고, 아파라!","WELL THAT HURT!",2,"치료킷 소모율 25% 증가"],["incompetent","폐급","INCOMPETENT",10,"스킬 성장 감소, 상한 30"],["polydipsia","다갈증","POLYDIPSIA",2,"수분 소모 15% 증가"],["fatigue","만성 피로 증후군","CHRONIC FATIGUE SYNDROME",2,"에너지 소모 20% 증가"],["vacuum","진상 손님","PERSONALITY VACUUM",2,"카리스마 성장 불가, 판매가 증가"],["jekyll","지킬 박사","DR. JEKYLL",1,"개방성 상처가 레이드 종료까지 유지"],["allergic","알레르기 체질","ALLERGIC",3,"식품·의약품 무작위 3개 알레르기"],["container","보안 컨테이너 파손","BROKEN SECURE CONTAINER",6,"보안 컨테이너 수납 품목 제한"],["noflea","플리마켓 금지령","NO FLEA MARKET",10,"플리마켓 유저 거래 불가"],["thirdleg","다리 사이의 다리","THIRD LEG",1,"이동 속도 감소, 테라피스트 판매가 인하"],["unlucky","언럭키","UNLUCKY",1,"때때로 치명적인 불운 발생"]
];
const GLOBAL=[
{en:["NO INSURANCE","Cannot insure items before raid"],ko:["보험 불가능","레이드 시작 전에 보험을 할 수 없습니다"],ja:["保険なし","アイテムの保険加入不可"]},
{en:["BLACK DIVISION","Black Division operatives can be encountered on specific locations"],ko:["블랙 디비전","특정 지역에서 블랙 디비전 대원들을 조우할 수 있습니다"],ja:["ブラックディビジョン","特定の場所でブラックディビジョンと遭遇することがあります"]},
{en:["NO FIR FOR HIDEOUT","Hideout zones do not require Found in Raid status"],ko:["은신처 인레이드 미요구","은신처 건설 및 업그레이드 재료에 인레이드 상태가 필요하지 않습니다"],ja:["ハイドアウトのFIR免除","ハイドアウトにはFIR状態が不要です"]},
{en:["ARMOR SHORTAGE","Traders across Tarkov are experiencing an armor shortage"],ko:["방어구 대란","타르코프 전역의 상인들이 방어구 대란을 겪습니다"],ja:["防弾ベスト不足","トレーダーが防弾ベスト不足に悩まされています"]},
{en:["HANDYMAN","Crafting time is reduced by 50%; Crafting starts at level 51"],ko:["만능 재주꾼","제작 시간이 50% 감소하고 제작 스킬을 51레벨로 시작합니다"],ja:["万能修理工","クラフト時間が50%短縮され、クラフトスキルがレベル51から始まります"]},
{en:["SEASONED PMCS","Your character gains 25% more raid experience"],ko:["베테랑 PMC","캐릭터의 레이드 경험치 획득량이 25% 증가합니다"],ja:["熟練したPMC","レイド経験値が25%増加します"]}
];
const EXCLUSIONS=[["thrombo","hemophilia"],["bones","osteoporosis"],["hypodipsia","polydipsia"],["polyphagia","fatigue"],["youth","fatigue"],["youth","exhaustion"],["average","incompetent"],["marathon","sprinter"],["marathon","exhaustion"],["shooter","average"],["polyphagia","youth"],["polyphagia","exhaustion"],["average","hercules"],["average","prodigy"],["prodigy","incompetent"],["lucky","unlucky"],["sprinter","thirdleg"],["vacuum","thirdleg"]];
const ACHIEVEMENTS=[
{name:{ko:"도움 필요 없어",en:"Don't Need Any Help",ja:"助けは要らない"},check:()=>POS.every(x=>!selected.has(x[0])),note:{ko:"긍정 퍽 없이 레벨 30 달성",en:"Reach level 30 with no positive perks",ja:"プラス特性なしでレベル30到達"}},
{name:{ko:"계획이 있었어",en:"I Had a Plan",ja:"計画があった"},check:()=>NEG.filter(x=>selected.has(x[0])).length>=10,note:{ko:"부정 특성 10개 이상으로 레벨 30 달성",en:"Reach level 30 with at least 10 negative traits",ja:"マイナス特性10個以上でレベル30到達"}},
{name:{ko:"유전자 복권",en:"Genetic Lottery",ja:"遺伝子の宝くじ"},ids:["hemophilia","osteoporosis","polydipsia","allergic","thirdleg"],note:{ko:"지정된 부정 특성 5개 선택 후 레벨 30 달성",en:"Pick the five specified negative traits and reach level 30",ja:"指定されたマイナス特性5個でレベル30到達"}},
{name:{ko:"하나도 좋지만, 둘은 더 좋다",en:"One Is Good, Two Is Better",ja:"一つも良いが二つはもっと良い"},ids:["kappa"],note:{ko:"카파 프로토콜 선택 및 추가 카파 획득",en:"Select Kappa Protocol and obtain another Kappa",ja:"カッパプロトコルを選択し、追加のカッパを入手"}},
{name:{ko:"우리 집에는 하드코어가 있다",en:"We Have Hardcore at Home",ja:"我が家にはハードコアがある"},ids:["container","noflea"],note:{ko:"보안 컨테이너 파손·플리마켓 금지령 선택 후 카파 정식 획득",en:"Pick Broken Secure Container and No Flea Market, then obtain Kappa normally",ja:"破損コンテナ・フリーマーケット禁止を選び、正規にカッパを入手"}},
{name:{ko:"그걸 도전이라고?",en:"You Call That a Challenge?",ja:"それが挑戦だって？"},pool:["marathon","youth","hercules","thrombo","hypodipsia","polyphagia","bones","prodigy"],need:5,note:{ko:"생존 계열 긍정 특성 중 5개 선택 후 모든 생존 경로 임무 완료",en:"Pick 5 survival perks and finish every survival-path task",ja:"生存系パークを5個選び、全サバイバル任務を完了"}},
{name:{ko:"천생 기업가",en:"Entrepreneur Born in Heaven",ja:"生まれながらの起業家"},ids:["tax"],note:{ko:"보호비 선택 후 5억₽·100만€·100만$ 동시 보유",en:"Pick Street Tax and hold 500M₽, 1M€, and 1M$ at once",ja:"みかじめ料を選び、5億₽・100万€・100万$を同時保有"}}
];
const OTHER_SEASON_ACHIEVEMENTS=[
{name:{ko:"신봉자",en:"Believer",ja:"信奉者"},note:{ko:"시즌 캐릭터로 레벨 30 달성",en:"Reach level 30 with a seasonal character",ja:"シーズンキャラクターでレベル30に到達"}},
{name:{ko:"일급비밀",en:"Top Secret",ja:"トップシークレット"},note:{ko:"기밀 문서를 제외한 모든 종류의 테라그룹 문서를 인벤토리에 보유",en:"Have every type of TerraGroup documentation in your inventory, excluding Classified Documents",ja:"機密文書を除く全種類のTerraGroup文書をインベントリに所持"}},
{name:{ko:"사칭자",en:"Imposter",ja:"偽者"},note:{ko:"블랙 디비전 장비를 사용해 블랙 디비전 대원 100명 처치",en:"Eliminate 100 Black Division operatives while using their equipment",ja:"Black Division装備を使用してBlack Division隊員を100人排除"}},
{name:{ko:"새로운 시대의 여명",en:"Dawn of a New Era",ja:"新時代の夜明け"},note:{ko:"시즌 시스템 도입 이후 카파 보안 컨테이너 획득",en:"Obtain Secure container Kappa after the Seasons system was introduced",ja:"シーズンシステム導入後にKappaセキュアコンテナを獲得"}},
{name:{ko:"원칙보다 이익",en:"Profit Over Principles",ja:"原則より利益"},note:{ko:"시즌 1 KORD BREACH의 펜스 퀘스트 라인을 완료하고 미확인 시설의 노트북을 메카닉 또는 펜스에게 전달",en:"Complete Fence's KORD BREACH task line and hand the unknown-facility laptop to Mechanic or Fence",ja:"Season 1 KORD BREACHのFenceタスクラインを完了し、未知の施設のノートPCをMechanicまたはFenceに渡す"}}
];
const QUEST_SUBQUESTS=new Set([2,7,13]);
const QUEST_LEVELS=[
  {ko:"프라퍼 우호도 2",en:"Prapor LL2",ja:"Prapor LL2"},null,null,null,null,null,
  {ko:"레벨 20",en:"LEVEL 20",ja:"レベル20"},null,null,null,null,null,null,null,null,null
];
const TRADER_PORTRAITS={
  "프라퍼":"https://assets.tarkov.dev/54cb50c76803fa8b248b4571.webp",
  "테라피스트":"https://assets.tarkov.dev/54cb57776803fa99248b456e.webp",
  "펜스":"https://assets.tarkov.dev/579dc571d53a0658a154fbec.webp",
  "라그맨":"https://assets.tarkov.dev/5ac3b934156ae10c4430e83c.webp",
  "메카닉":"https://assets.tarkov.dev/5a7c2eca46aef81a7ca2145d.webp",
  "예거":"https://assets.tarkov.dev/5c0647fdd443bc2504c2d371.webp"
};
function questDisplayNumber(index){return QUESTS.slice(0,index+1).filter((_,candidate)=>!QUEST_SUBQUESTS.has(candidate)).length}
const QUESTS=[
["Uninvited Guests - Part 1","프라퍼","군용 장비가 든 케이스 1개를 찾아 획득"],["Uninvited Guests - Part 2","BTR 운전수","군용 장비가 든 케이스 1개를 BTR 운전수에게 제출"],["Unanswered Calls","테라피스트","그라운드 제로 테라그룹 사무실 2층 접수대에 편지 1개 설치 (한 레이드)"],["Cast the Net","프라퍼","해안선·타르코프 시내·그라운드 제로의 지정 장소 6곳에 WI-FI 카메라 설치"],["Know Your Enemy","프라퍼","블랙 디비전 플레이트 캐리어 아무 종류 5개 제출"],["Reverse Gear","프라퍼","Cast the Net에서 설치한 WI-FI 카메라 6개 회수 후 제출"],["Key to Understanding","펜스","블랙 디비전 암호화 키 1개를 인레이드 상태로 획득해 제출"],["Riding the Wave","라그맨","지정된 블랙 디비전 장비 10종을 각 1개씩 인레이드 상태로 제출"],["What's in the Bag?","프라퍼","문서가 든 서류가방 1개를 인레이드 상태로 제출"],["Forbidden Knowledge","프라퍼","14-4 KORD SSD 3개를 인레이드 상태로 제출"],["Wolf in Sheep's Clothing","프라퍼","블랙 디비전 플레이트 캐리어 착용 후 3개 지역에서 각각 4명 처치"],["Final Stretch","펜스","타르코프 시내의 은닉처에서 노트북 1개를 획득해 제출"],["Desperate Assault","메카닉","연구소에서 블랙 디비전 대원 15명 처치"],["Stay Clear of Blast Zone","예거","해안선 리조트 담장 파손 지점 3곳에 TP-200 TNT 각 1개 설치"],["Break the Chain","메카닉","세관 2곳과 삼림 2곳의 송신기 총 4개 파괴"],["Digital Puzzle","메카닉","블랙 디비전 러기드 노트북을 복호화해 데이터 1개 제출"]
];
const QUEST_GOALS={en:["Find and obtain the case containing military equipment","Obtain and hand over the case containing military equipment","Plant the letter at the second-floor reception desk of the TerraGroup office on Ground Zero in one raid","Plant WI-FI cameras at six designated locations on Shoreline, Streets, and Ground Zero","Hand over any five Black Division armored rigs","Retrieve the six WI-FI cameras planted during Cast the Net","Obtain the Black Division encryption key","Hand over ten specified Black Division equipment items found in raid","Obtain the briefcase containing documents","Obtain three 14-4 KORD SSDs","While wearing a Black Division rig, eliminate four Black Division members on each of Shoreline, Streets, and Ground Zero","Retrieve and hand over the laptop from Fence's stash on Streets","Eliminate 15 Black Division members in The Lab","Plant TP-200 TNT at the damaged fence sections west, north, and east of the Shoreline resort","Destroy two transmitters on Customs and two on Woods","Hand over the data extracted from the Black Division rugged laptop"],ja:["軍用装備入りケースを発見して入手する","軍用装備入りケースを入手して引き渡す","Ground ZeroのTerraGroup事務所2階受付に手紙を設置する（1レイド）","Shoreline・Streets・Ground Zeroの指定6地点にWI-FIカメラを設置する","Black Divisionのアーマーリグを5個引き渡す","Cast the Netで設置したWI-FIカメラ6台を回収する","Black Divisionの暗号化キーを入手する","指定されたBlack Division装備10種をFound in Raid状態で引き渡す","文書入りブリーフケースを入手する","14-4 KORD SSDを3個入手する","Black Divisionリグを装備し、Shoreline・Streets・Ground Zeroで各4人を排除する","StreetsのFenceの隠し場所からノートPCを回収して引き渡す","The LabでBlack Divisionを15人排除する","Shorelineリゾート西・北・東の破損フェンスにTP-200 TNTを設置する","Customsで2台、Woodsで2台の送信機を破壊する","Black DivisionのラギッドノートPCから抽出したデータを引き渡す"]};
const QUEST_GUIDES={
ko:["해안선의 3개 후보 지점 중 1곳에서 1개 획득: 소르디 타워 옆 오두막, 기상 관측소 2층, 발전소 1층.","Part 1에서 얻은 군용 장비 케이스 1개를 삼림 또는 타르코프 시내의 BTR 정류장에서 BTR 운전수에게 제출.","테라그룹 본사 2층 접수대에 테라피스트의 편지 1개 설치. 설치 전후 사망하거나 EMERCOM 검문소·나카타니 지하가 아닌 탈출구를 사용하면 실패.","WI-FI 카메라 총 6개 필요: 해안선 수력발전소 우랄 트럭·밀수꾼 기지 하천 굴착기, 시내 무너진 크레인 콘크리트 믹서·로디나 영화관 앞 이동식 화장실, 그제 미라 애비뉴 화물트럭 운전석·지하 노란 버스에 각 1개.","블랙 디비전 방탄 플레이트 캐리어 아무 종류 5개 제출. 그제(레벨 21+), 해안선, 시내 및 연구소의 블랙 디비전에게서 획득.","Cast the Net에서 설치한 카메라 6개를 같은 장소에서 각각 회수해 제출.","일반 지역을 순찰하는 블랙 디비전에게서 인레이드 암호화 키 1개 획득 후 제출. 쇄빙선에서는 획득 불가.","인레이드 상태로 각 1개 제출: Siege-R·LV-119 V1·LV-119 V2·FCPC V5 캐리어, Modular Pack 45 Plus·2 Day Assault Pack·NICE Frame Load Sling, M53A1 방독면·SOTR 호흡기·Gatorz Specter 안경. 블랙 디비전 장비에서 획득.","문서가 든 서류가방 1개를 인레이드 상태로 제출. Reverse Gear 보상, 컬티스트 서클에서 블랙 디비전 토큰 5개 교환, 또는 블랙 디비전 희귀 드롭으로 획득.","14-4 KORD SSD 3개를 인레이드 상태로 제출. 블랙 디비전 구역에서 확률적으로 생성되며 시내·해안선·연구소에서 찾기 쉬움. 쇄빙선 제외.","블랙 디비전 플레이트 캐리어 착용 필수. 해안선 4명 + 시내 4명 + 그라운드 제로 4명, 총 12명 처치.","타르코프 시내 Sparja 맞은편 건물 사이 통로의 카페로 들어가 흰 문 왼쪽 환기구에서 노트북 1개 획득 후 펜스에게 제출.","연구소에서 블랙 디비전 대원 15명 처치. 탈출구를 작동시키면 등장하는 병력도 대상.","TP-200 TNT 3개 필요. 해안선 리조트의 서쪽·북쪽·동쪽 담장 파손 지점에 각각 1개 설치.","송신기 총 4개 파괴: 세관 미완공 건설현장 인근 공장 굴뚝·송전탑, 삼림 산 정상·통신탑에 각 1개.","블랙 디비전 러기드 노트북은 블랙 디비전에게서 획득할 수 있습니다(쇄빙선 제외). 정보센터 1레벨에서 복호화한 데이터 1개를 메카닉에게 제출."],
en:["Find 1 case at one of three Shoreline spawns: the shack by Sordi tower, Weather Station second floor, or Power Station first floor.","Take the case from Part 1 to a BTR stop on Woods or Streets and hand 1 case to the BTR Driver.","Plant Therapist's letter at the TerraGroup HQ second-floor reception. Dying or using an extract other than EMERCOM Checkpoint or Nakatani Basement fails the task.","Bring 6 WI-FI Cameras: place one at each Shoreline Ural truck and excavator, Streets concrete mixer and Rodina portable toilet, and Ground Zero cargo truck cab and underground yellow bus.","Hand over any 5 Black Division plate carriers, looted from Black Division on Ground Zero (level 21+), Shoreline, Streets, or The Lab.","Recover and hand over all 6 cameras from the same locations used in Cast the Net.","Loot 1 Found in Raid encryption key from Black Division roaming standard locations and hand it over. It cannot be obtained on Icebreaker.","Hand over 1 Found in Raid item of each type: Siege-R, LV-119 V1, LV-119 V2 and FCPC V5 carriers; Modular Pack 45 Plus, 2 Day Assault Pack and NICE Frame Load Sling; M53A1, SOTR and Gatorz Specter.","Hand over 1 Found in Raid briefcase. Obtain it from the Reverse Gear reward, exchange 5 Black Division tokens at the Cultist Circle, or find it as a rare Black Division drop.","Hand over 3 Found in Raid 14-4 KORD SSDs. They can spawn in Black Division areas, most commonly on Streets, Shoreline, and The Lab. Icebreaker excluded.","Wear a Black Division plate carrier and eliminate 4 operatives on Shoreline, 4 on Streets, and 4 on Ground Zero: 12 total.","On Streets, enter the cafe through the passage opposite Sparja, use the white door, and take 1 laptop from the ventilation shaft; hand it to Fence.","Eliminate 15 Black Division operatives in The Lab; operatives spawned after an extract is activated also count.","Bring 3 TP-200 TNT bricks and plant one at each west, north, and east Health Resort fence breach on Shoreline.","Destroy 4 transmitters: the factory chimney and power-line tower on Customs, plus the mountain top and cell tower on Woods.","Obtain a Black Division rugged laptop from Black Division operatives (excluding Icebreaker), decrypt it at Intelligence Center level 1, and hand 1 data item to Mechanic."],
ja:["Shorelineの候補3か所（Sordi塔横の小屋、気象観測所2階、発電所1階）のいずれかでケース1個を入手。","Part 1のケース1個をWoodsまたはStreetsのBTR停留所でBTR Driverに引き渡す。","TerraGroup本社2階受付にTherapistの手紙1通を設置。設置前後の死亡、またはEMERCOM Checkpoint・Nakatani Basement以外の脱出で失敗。","WI-FI Cameraを計6台用意。ShorelineのUralトラック・掘削機、Streetsのコンクリートミキサー・Rodina前の仮設トイレ、Ground Zeroのトラック運転席・地下の黄色いバスに各1台。","Black Divisionのプレートキャリアを種類不問で5個引き渡す。Ground Zero（Lv21以上）、Shoreline、Streets、The Labで入手。","Cast the Netで設置した同じ6か所からカメラを回収して引き渡す。","通常マップを巡回するBlack DivisionからFound in Raidの暗号鍵1個を入手して引き渡す。Icebreakerでは入手不可。","Found in Raidで各1個：Siege-R、LV-119 V1/V2、FCPC V5、Modular Pack 45 Plus、2 Day Assault Pack、NICE Frame Load Sling、M53A1、SOTR、Gatorz Specter。","Found in Raidの文書入りブリーフケース1個を提出。Reverse Gear報酬、Cultist Circleでトークン5個と交換、またはBlack Divisionのレアドロップで入手。","Found in Raidの14-4 KORD SSDを3個提出。Black Divisionエリアで確率出現し、Streets・Shoreline・The Labで見つけやすい。Icebreakerを除く。","Black Divisionのプレートキャリアを装備し、Shorelineで4人、Streetsで4人、Ground Zeroで4人、合計12人を排除。","StreetsのSparja向かいの建物間通路からカフェへ入り、白い扉の左側にある換気口からノートPC1台を回収してFenceへ提出。","The LabでBlack Divisionを15人排除。脱出口作動後に出現する部隊も対象。","TP-200 TNTを3個用意し、Shorelineリゾート西・北・東のフェンス破損部に各1個設置。","送信機4基を破壊：Customsの工場煙突・送電塔、Woodsの山頂・通信塔に各1基。","Black Divisionからrugged laptopを入手可能（Icebreakerを除く）。Intelligence Center Lv.1で復号し、データ1個をMechanicへ提出。"]
};
QUESTS[11][1]="펜스+메카닉";
QUESTS[11][0]="Final Stretch / Consequences of Our Decisions";
QUESTS[11][2]="같은 노트북을 펜스에게 제출하거나 메카닉에게 복호화해 제출하는 선택형 퀘스트";
QUEST_GOALS.en[11]="Choose one route for the same laptop: hand it to Fence, or decrypt it and hand it to Mechanic";
QUEST_GOALS.ja[11]="同じノートPCをFenceへ渡すか、復号してMechanicへ渡すか、どちらか一方を選択";
QUEST_LEVELS[11]={ko:"택1",en:"CHOOSE ONE",ja:"どちらか1つ"};
QUEST_GUIDES.ko[11]="Final Stretch와 Consequences of Our Decisions는 상호 배타 선택지입니다. 같은 노트북을 펜스에게 바로 제출하거나, 정보센터 1레벨에서 복호화해 메카닉에게 제출하세요. 어느 쪽을 선택해도 Desperate Assault로 이어집니다.";
QUEST_GUIDES.en[11]="Final Stretch and Consequences of Our Decisions are mutually exclusive. Give the laptop directly to Fence, or decrypt it at Intelligence Center level 1 and give it to Mechanic. Either route unlocks Desperate Assault.";
QUEST_GUIDES.ja[11]="Final StretchとConsequences of Our Decisionsは排他的な選択肢です。ノートPCをFenceへ直接渡すか、Intelligence Center Lv.1で復号してMechanicへ渡します。どちらを選んでもDesperate Assaultへ進みます。";
QUEST_GUIDES.ko[4]="블랙 디비전 방탄 플레이트 캐리어 아무 종류 5개 제출. 그제(레벨 21+), 해안선, 시내, 연구소 또는 쇄빙선에서 획득. 쇄빙선의 웨지가 착용하는 LV-119 MultiCam Black도 제출 가능.";
QUEST_GUIDES.en[4]="Hand over any 5 Black Division plate carriers, obtained on Ground Zero (level 21+), Shoreline, Streets, The Lab, or Icebreaker. The LV-119 MultiCam Black worn by The Wedge on Icebreaker is also accepted.";
QUEST_GUIDES.ja[4]="Black Divisionのプレートキャリアを種類不問で5個引き渡す。Ground Zero（Lv21以上）、Shoreline、Streets、The Lab、またはIcebreakerで入手可能。IcebreakerのThe Wedgeが装備するLV-119 MultiCam Blackも提出できる。";
const BRIEFCASE_WIKI="https://escapefromtarkov.fandom.com/wiki/Briefcase_with_documents";
QUEST_GUIDES.ko[5]+=`<br><span class="quest-reward-inline"><b>퀘스트 보상:</b> <a href="${BRIEFCASE_WIKI}" target="_blank" rel="noopener noreferrer">서류가 든 서류 가방</a> — 후속 퀘스트 What's in the Bag?에 제출해야 하므로 보관하세요.</span>`;
QUEST_GUIDES.en[5]+=`<br><span class="quest-reward-inline"><b>Quest reward:</b> <a href="${BRIEFCASE_WIKI}" target="_blank" rel="noopener noreferrer">Briefcase with documents</a> — keep it for the follow-up quest What's in the Bag?.</span>`;
QUEST_GUIDES.ja[5]+=`<br><span class="quest-reward-inline"><b>クエスト報酬：</b> <a href="${BRIEFCASE_WIKI}" target="_blank" rel="noopener noreferrer">書類入りブリーフケース</a> — 後続クエストWhat's in the Bag?で提出するため保管してください。</span>`;
QUEST_GUIDES.ko[7]="인레이드 상태로 각 1개 제출: Siege-R·LV-119 V1·LV-119 V2·FCPC V5 캐리어, Modular Pack 45 Plus·2 Day Assault Pack·NICE Frame Load Sling, M53A1 방독면·SOTR 호흡기·Gatorz Specter 안경. 블랙 디비전 상자에서 획득 가능.";
QUEST_GUIDES.en[7]="Hand over 1 Found in Raid item of each type: Siege-R, LV-119 V1, LV-119 V2 and FCPC V5 carriers; Modular Pack 45 Plus, 2 Day Assault Pack and NICE Frame Load Sling; M53A1, SOTR and Gatorz Specter. Available from Black Division crates.";
QUEST_GUIDES.ja[7]="Found in Raidで各1個：Siege-R、LV-119 V1/V2、FCPC V5、Modular Pack 45 Plus、2 Day Assault Pack、NICE Frame Load Sling、M53A1、SOTR、Gatorz Specter。Black Divisionクレートから入手可能。";
const QUEST_WIKI=QUESTS.map(q=>q[0]==="Wolf in Sheep's Clothing"?"https://escapefromtarkov.fandom.com/wiki/Sheep_in_Wolf%27s_Clothing":`https://escapefromtarkov.fandom.com/wiki/${encodeURIComponent(q[0].replaceAll(" ","_"))}`);
QUEST_WIKI[11]="";
const CHOICE_REWARDS={
ko:[
{title:"Final Stretch · 펜스 선택",wiki:"https://escapefromtarkov.fandom.com/wiki/Final_Stretch",items:["경험치 35,000","300,000 ₽","문서가 든 서류가방","RB-BK 마크방 열쇠 ×1"]},
{title:"Consequences of Our Decisions · 메카닉 선택",wiki:"https://escapefromtarkov.fandom.com/wiki/Consequences_of_Our_Decisions",items:["경험치 35,000","300,000 ₽","문서가 든 서류가방","전동 드릴 ×5","군용 COFDM 무선 신호 송신기 ×3","Cyclon 충전식 배터리 ×5","공구 세트 ×5"]}
],
en:[
{title:"Final Stretch · Fence route",wiki:"https://escapefromtarkov.fandom.com/wiki/Final_Stretch",items:["35,000 EXP","300,000 ₽","Briefcase with documents","RB-BK marked key ×1"]},
{title:"Consequences of Our Decisions · Mechanic route",wiki:"https://escapefromtarkov.fandom.com/wiki/Consequences_of_Our_Decisions",items:["35,000 EXP","300,000 ₽","Briefcase with documents","Electric drill ×5","Military COFDM Wireless Signal Transmitter ×3","Cyclon rechargeable battery ×5","Toolset ×5"]}
],
ja:[
{title:"Final Stretch · Fenceルート",wiki:"https://escapefromtarkov.fandom.com/wiki/Final_Stretch",items:["経験値 35,000","300,000 ₽","書類入りブリーフケース","RB-BKマークドキー ×1"]},
{title:"Consequences of Our Decisions · Mechanicルート",wiki:"https://escapefromtarkov.fandom.com/wiki/Consequences_of_Our_Decisions",items:["経験値 35,000","300,000 ₽","書類入りブリーフケース","電動ドリル ×5","軍用COFDM無線信号送信機 ×3","Cyclon充電式バッテリー ×5","ツールセット ×5"]}
]};
const QUEST_AREAS=["Shoreline","Streets · Woods","Ground Zero","Shoreline · Streets · Ground Zero","Any location","Shoreline · Streets · Ground Zero","Black Division loot","Found in Raid equipment","Quest item","Quest item","Shoreline · Streets · Ground Zero","Streets","The Lab","Shoreline","Customs · Woods","Intelligence Center Lv. 1"];
const QUEST_ITEM_ASSET="https://tarkov101.com/img/season/";
const questItem=(name,file,qty=1)=>({name,icon:`${QUEST_ITEM_ASSET}${file}`,qty});
const QUEST_ITEMS=[
  [questItem("Case with military equipment","case-with-military-equipment-icon.webp")],
  [questItem("Case with military equipment","case-with-military-equipment-icon.webp")],
  [questItem("Therapist's message","therapist-s-message-icon.webp")],
  [questItem("WI-FI Camera","wifi-camera-icon.webp",6)],
  [
    questItem("FCPC V5 Black Division","ferro-concepts-fcpc-v5-plate-carrier-black-division-icon.webp",null),
    questItem("Siege-R Black Division","first-spear-siege-r-optimized-m-a-s-s-plate-carrier-black-division-icon.webp",null),
    questItem("LV-119 Black Division V1","spiritus-systems-lv-119-plate-carrier-black-division-v1-icon.webp",null),
    questItem("LV-119 Black Division V2","spiritus-systems-lv-119-plate-carrier-black-division-v2-icon.webp",null),
    questItem("LV-119 MultiCam Black","spiritus-systems-lv-119-plate-carrier-multicam-black-icon.webp",null)
  ],
  [questItem("WI-FI Camera","wifi-camera-icon.webp",6)],
  [questItem("Black Division encryption keys","black-division-encryption-keys-icon.webp")],
  [
    questItem("Siege-R Black Division","first-spear-siege-r-optimized-m-a-s-s-plate-carrier-black-division-icon.webp"),
    questItem("LV-119 Black Division V1","spiritus-systems-lv-119-plate-carrier-black-division-v1-icon.webp"),
    questItem("LV-119 Black Division V2","spiritus-systems-lv-119-plate-carrier-black-division-v2-icon.webp"),
    questItem("FCPC V5 Black Division","ferro-concepts-fcpc-v5-plate-carrier-black-division-icon.webp"),
    questItem("Modular Pack 45 Plus","tasmanian-tiger-modular-pack-45-plus-multicam-black-icon.webp"),
    questItem("2 Day Assault Pack","mystery-ranch-2-day-assault-pack-black-icon.webp"),
    questItem("NICE Frame Load Sling","mystery-ranch-nice-frame-load-sling-icon.webp"),
    questItem("M53A1 gas mask","avon-m53a1-gas-mask-icon.webp"),
    questItem("SOTR respirator","gentex-ops-core-sotr-respirator-icon.webp"),
    questItem("Gatorz Specter glasses","gatorz-specter-milspec-ballistic-glasses-icon.webp")
  ],
  [questItem("Briefcase with documents","briefcase-with-documents-icon.webp")],
  [
    questItem("14-4 KORD SSD","14-4-kord-ssd-icon.webp"),
    questItem("14-4 KORD SSD","14-4-kord-ssd-icon.webp"),
    questItem("14-4 KORD SSD","14-4-kord-ssd-icon.webp")
  ],
  [
    questItem("FCPC V5 Black Division","ferro-concepts-fcpc-v5-plate-carrier-black-division-icon.webp",null),
    questItem("Siege-R Black Division","first-spear-siege-r-optimized-m-a-s-s-plate-carrier-black-division-icon.webp",null),
    questItem("LV-119 Black Division V1","spiritus-systems-lv-119-plate-carrier-black-division-v1-icon.webp",null),
    questItem("LV-119 Black Division V2","spiritus-systems-lv-119-plate-carrier-black-division-v2-icon.webp",null),
    questItem("LV-119 MultiCam Black","spiritus-systems-lv-119-plate-carrier-multicam-black-icon.webp",null)
  ],
  [questItem("Laptop from an unknown facility","laptop-from-an-unknown-facility-icon.webp")],
  [],
  [questItem("TP-200 TNT brick","tnt-brick-icon.webp",3)],
  [],
  [questItem("Black Division rugged laptop","black-division-rugged-laptop-icon.webp"),questItem("Data from Black Division laptop","data-from-black-division-laptop-icon.webp")]
];
const ADDITIONAL_SEASON_QUESTS=[
  {
    "name": "Price for Information",
    "area": "Shoreline → Lighthouse → Reserve → Woods",
    "goals": {
      "ko": "한 번의 연속 레이드에서 해안선 → 등대 → 리저브 → 우드로 트랜짓하고, 다른 목표 진행 중 블랙디비전을 제외한 대상 총 10명 처치",
      "en": "Transit Shoreline → Lighthouse → Reserve → Woods in one continuous raid, and eliminate 10 targets other than Black Division while completing the other objectives",
      "ja": "1回の連続レイドでShoreline → Lighthouse → Reserve → Woodsへ移動し、他の目標を進めながらBlack Division以外を合計10人排除する"
    },
    "guides": {
      "ko": "해안선에서 시작해 지정된 트랜짓 3개를 순서대로 이용하세요. 한 번의 연속 레이드에서 다른 목표를 진행하면서 블랙 디비전을 제외한 대상을 총 10명 처치해야 합니다. 블랙 디비전과는 교전하지 마세요.",
      "en": "Start on Shoreline and use all three transits in order. During the same continuous raid, eliminate 10 targets other than Black Division while completing the other objectives. Do not engage Black Division.",
      "ja": "Shorelineから開始し、指定のトランジット3か所を順番に利用します。同じ1回の連続レイド中に、他の目標を進めながらBlack Division以外の対象を合計10人排除する必要があります。Black Divisionとは交戦しないでください。"
    }
  },
  {
    "name": "Historical Prospects",
    "area": "Customs · Woods · Streets of Tarkov",
    "goals": {
      "ko": "게임 시간 22:00~08:00에 세관·우드·타르코프 시내에서 PMC를 각각 3명 처치하고, 각 지역 지정 장소에 PMC 인식표 3개씩 설치 (총 9명·9개)",
      "en": "Eliminate 3 PMCs each on Customs, Woods and Streets of Tarkov during 22:00–08:00 in-game, and stash 3 PMC dogtags at each designated site (9 kills and 9 dogtags total)",
      "ja": "ゲーム内時間22:00～08:00にCustoms・Woods・Streets of TarkovでPMCを各3人排除し、各指定地点にPMCドッグタグを3個ずつ設置（合計9人・9個）"
    },
    "guides": {
      "ko": "설치할 PMC 인식표는 인레이드(Found in Raid) 상태이면 됩니다. 퀘스트는 여러 레이드에 걸쳐 진행할 수 있으며, 한 번의 레이드에서 모두 완료할 필요는 없습니다. 설치 장소: 세관 마크방, 우드 버려진 마을 마크 서클, 타르코프 시내 Nikitskaya St. 8 건물 2층 아파트 마크 서클. 설치 목표에는 별도 시간 제한이 표기돼 있지 않습니다.",
      "en": "PMC dogtags to be stashed must have Found in Raid status. You can progress across multiple raids; the quest does not have to be completed in a single raid. Stash locations: the marked room on Customs; the abandoned village marked circle on Woods; the marked circle in the second-floor apartment at Nikitskaya St. 8 on Streets. The stash objectives do not list a time restriction.",
      "ja": "設置するPMCドッグタグはFound in Raid状態であれば使用できます。クエストは複数のレイドに分けて進められ、1回のレイドですべて完了する必要はありません。設置場所：Customsのマークド部屋、Woodsの廃村のマークドサークル、StreetsのNikitskaya St. 8の2階アパート内マークドサークル。設置目標には時間制限の記載がありません。"
    }
  }
];
const QUEST_UNNUMBERED=new Set();
for(const quest of ADDITIONAL_SEASON_QUESTS){
  const index=QUESTS.length;
  QUEST_UNNUMBERED.add(index);
  QUESTS.push([quest.name,"등대지기",quest.goals.ko]);
  QUEST_AREAS.push(quest.area);
  QUEST_ITEMS.push([]);
  QUEST_WIKI.push("");
  for(const lang of LANGUAGES){
    if(lang!=="ko")QUEST_GOALS[lang].push(quest.goals[lang]);
    QUEST_GUIDES[lang].push(quest.guides[lang]);
  }
}
TRADER_PORTRAITS["등대지기"]="https://assets.tarkov.dev/638f541a29ffd1183d187f57.webp";
UI.ko.questDesc="시즌 퀘스트 목표와 보상을 정리했습니다.";
UI.en.questDesc="Season quest objectives and rewards.";
UI.ja.questDesc="シーズンクエストの目標と報酬。";

const TRADERS={"등대지기":"Lightkeeper","프라퍼":"Prapor","테라피스트":"Therapist","펜스":"Fence","라그맨":"Ragman","메카닉":"Mechanic","예거":"Jaeger","BTR 운전수":"BTR Driver"};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let allergy=read(KEYS.allergy,{}),selected=new Set(read(KEYS.modifiers,[])),questsDone=new Set(read(KEYS.questsDone,[])),seasonAchievementsDone=new Set(read(KEYS.seasonAchievementsDone,[])),otherAchievementsDone=new Set(read(KEYS.otherAchievementsDone,[])),kappaItems=new Set(read(KEYS.kappaItems,[])),kappaRequirements=new Set(read(KEYS.kappaRequirements,[])),filter="전체",query="";
if(kappaRequirements.has("trader-ll4")){kappaRequirements.delete("trader-ll4");["trader-prapor-ll4","trader-therapist-ll4","trader-skier-ll4","trader-peacekeeper-ll4","trader-mechanic-ll4","trader-ragman-ll4","trader-jaeger-ll4"].forEach(id=>kappaRequirements.add(id));localStorage.setItem(KEYS.kappaRequirements,JSON.stringify([...kappaRequirements]))}
EXCLUSIONS.forEach(([a,b])=>{if(selected.has(a)&&selected.has(b))selected.delete(b)});
function closeMenu(){document.querySelector("#hub-nav").classList.remove("open");document.querySelector("#nav-backdrop").classList.remove("open")}
function renderHubSeasonCountdown(){const el=document.querySelector("#hub-season-countdown");if(!el)return;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),days=Math.ceil((HUB_SEASON_END-today)/86400000),dateLabel=language==="ko"?"종료 예정일":language==="ja"?"終了予定日":"SCHEDULED END";el.innerHTML=days>=0?(language==="ko"?`시즌 종료까지 D-${days}<small>${dateLabel} · 2026.12.07</small>`:language==="ja"?`終了まで D-${days}<small>${dateLabel} · 2026.12.07</small>`:`ENDS IN D-${days}<small>${dateLabel} · 2026.12.07</small>`):(language==="ko"?`시즌 종료<small>${dateLabel} · 2026.12.07</small>`:language==="ja"?`シーズン終了<small>${dateLabel} · 2026.12.07</small>`:`SEASON ENDED<small>${dateLabel} · 2026.12.07</small>`);el.classList.toggle("ended",days<0)}
function renderHubMapMenu(){const list=document.querySelector("#hub-map-buttons"),title=document.querySelector("#hub-map-menu>small");if(!list)return;if(title)title.textContent=language==="ko"?"맵 변경":language==="ja"?"マップ変更":"MAP CHANGE";list.innerHTML=HUB_MAPS.map(map=>`<button type="button" class="hub-map-button ${map.id===currentMap?"active":""}" data-hub-map="${map.id}"><span>${map.name[language]}</span><i>${map.docs.map(doc=>`<img src="/assets/document-icons/${HUB_DOCUMENT_ICONS[doc]}?v=1" alt="" width="18" height="18">`).join("")}</i></button>`).join("")}
function iframeUrl(view){return view==="documents"?`/document-map/?embedded=1&map=${encodeURIComponent(currentMap)}&lang=${language}`:`/?embedded=1&view=battlepass&lang=${language}`}
function setView(view,push=true){if(!VIEWS[view])view="battlepass";if(push&&view!==PAGE_VIEW){location.assign(VIEW_ROUTES[view]);return}currentView=view;document.querySelectorAll(".hub-tab").forEach(x=>x.classList.toggle("active",x.dataset.view===view));document.querySelectorAll(".hub-panel").forEach(x=>x.classList.toggle("active",x.dataset.panel===view));document.querySelector("#view-kicker").textContent=VIEWS[view][0];document.querySelector("#view-title").textContent=labelByLanguage[language][view];const frame=document.querySelector(`[data-panel="${view}"] iframe`);if(frame&&!frame.src)frame.src=iframeUrl(view);localStorage.setItem(KEYS.view,view);closeMenu()}
function setLanguage(next){if(!LANGUAGES.includes(next))return;language=next;localStorage.setItem(KEYS.language,language);document.documentElement.lang=language;document.querySelector("#hub-language").value=language;document.querySelectorAll(".hub-tab").forEach(tab=>{const label=tab.querySelector("span");if(label)label.firstChild.nodeValue=labelByLanguage[language][tab.dataset.view]});document.querySelectorAll(".hub-panel iframe").forEach(frame=>{if(frame.src)frame.src=iframeUrl(frame.closest(".hub-panel").dataset.panel)});filter="전체";renderHubSeasonCountdown();renderHubMapMenu();renderQuests();renderAllergy();renderModifiers();renderKappa();setView(currentView,false)}
function setMap(next){if(!HUB_MAPS.some(map=>map.id===next))return;currentMap=next;localStorage.setItem(KEYS.map,currentMap);renderHubMapMenu();const frame=document.querySelector('[data-panel="documents"] iframe');if(frame&&frame.src)frame.contentWindow.postMessage({type:"select-map",map:currentMap},location.origin);closeMenu()}
function traderIcon(trader){return trader.split("+").map(name=>{const label=language==="ko"?name:TRADERS[name],portrait=TRADER_PORTRAITS[name];return portrait?`<span class="quest-trader-icon" title="${label}" aria-label="${label}"><img src="${portrait}" alt="${label}" width="34" height="34" loading="lazy" decoding="async"></span>`:`<span class="quest-trader-icon btr-icon" title="${label}" aria-label="${label}">BTR</span>`}).join("")}
function renderChoiceRewards(){const heading=language==="ko"?"선택지별 보상":language==="ja"?"ルート別報酬":"Rewards by route",wikiLabel=language==="ko"?"퀘스트 위키":language==="ja"?"クエストWiki":"Quest Wiki",achievement={ko:"시즌 업적: 원칙보다 이익 달성",en:"Season Achievement: Profit Over Principles unlocked",ja:"シーズン実績：原則より利益 達成"}[language];return `<section class="choice-rewards"><h4>${heading}</h4><div>${CHOICE_REWARDS[language].map(route=>`<article><strong>${route.title}</strong><ul>${route.items.map(item=>`<li>${item}</li>`).join("")}</ul><a href="${route.wiki}" target="_blank" rel="noopener noreferrer">${wikiLabel} ↗</a></article>`).join("")}</div><p class="choice-achievement">${achievement}</p></section>`}
function renderHistoricalDogtags(){
  const label={ko:"PMC 인식표",en:"PMC dogtag",ja:"PMCドッグタグ"}[language];
  return '<div class="quest-dogtag-groups" style="display:flex;flex-wrap:wrap;gap:16px;margin:12px 0">'+["customs","woods","streets"].map(id=>{
    const map=HUB_MAPS.find(entry=>entry.id===id);
    return '<div><strong>'+map.name[language]+'</strong><div class="quest-items">'+Array.from({length:3},()=>'<span class="quest-item" title="'+label+'"><img src="https://assets.tarkov.dev/59f32c3b86f77472a31742f0-icon.webp" alt="'+label+'" width="44" height="44" loading="lazy" decoding="async"></span>').join("")+'</div></div>';
  }).join("")+'</div>';
}

function renderLightkeeperUnlockNotice(){
  const completed=read("tarkov-hub:lightkeeper-unlocked:v1",false)===true;
  const buttonLabel={ko:completed?"완료 취소":"완료",en:completed?"UNDO":"COMPLETE",ja:completed?"完了を取消":"完了"}[language];
  const copy={
    ko:{title:"등대지기 해금 필요",description:"이후 시즌 퀘스트를 진행하려면 등대지기를 해금해야 합니다.",link:"To the Light - Trust but Verify · 요구사항 확인"},
    en:{title:"Unlock Lightkeeper",description:"Unlock Lightkeeper to continue with the following season quests.",link:"To the Light - Trust but Verify · View requirements"},
    ja:{title:"Lightkeeperの解放が必要",description:"これ以降のシーズンクエストを進めるには、Lightkeeperを解放する必要があります。",link:"To the Light - Trust but Verify · 必要条件を確認"}
  }[language];
  const requirements={"ko":["스토리 챕터 Tour를 진행해 등대 직접 입장을 해금하세요.","프라퍼·테라피스트·스키어·피스키퍼·메카닉·라그맨·예거의 충성도를 모두 3레벨로 올리세요.","메카닉에게 등대지기와 함께 일할 수 있는지 문의하세요."],"en":["Progress through the Tour story chapter to unlock direct access to Lighthouse.","Reach Loyalty Level 3 with Prapor, Therapist, Skier, Peacekeeper, Mechanic, Ragman, and Jaeger.","Ask Mechanic about working with Lightkeeper."],"ja":["ストーリーチャプターTourを進め、Lighthouseへの直接入場を解放してください。","Prapor・Therapist・Skier・Peacekeeper・Mechanic・Ragman・Jaeger全員のロイヤリティレベルを3にしてください。","Lightkeeperと協力できるかMechanicに尋ねてください。"]}[language];
  const questChain=[[["Trust but Verify","To_the_Light_-_Trust_but_Verify"]],[["False Call","To_the_Light_-_False_Call"]],[["You Called?","To_the_Light_-_You_Called?"]],[["Clip Their Wings","To_the_Light_-_Clip_Their_Wings"]],[["Fallen Bird","To_the_Light_-_Fallen_Bird"]],[["Dangerous Ambitions","To_the_Light_-_Dangerous_Ambitions"],["Fiasco","To_the_Light_-_Fiasco"]],[["A Time to Scatter Stones","To_the_Light_-_A_Time_to_Scatter_Stones"]],[["A Time to Gather Stones","To_the_Light_-_A_Time_to_Gather_Stones"]],[["The Other Side","To_the_Light_-_The_Other_Side"]],[["Getting Acquainted","To_the_Light_-_Getting_Acquainted"]]];
  const chainLabel={ko:"등대지기 해금 퀘스트 순서",en:"Lightkeeper unlock quest order",ja:"Lightkeeper解放クエストの順序"}[language];
  const requirementsLabel={ko:"To the Light - Trust but Verify 시작 조건",en:"To the Light - Trust but Verify requirements",ja:"To the Light - Trust but Verifyの開始条件"}[language];
  return `<article class="quest-card ${completed?"completed":""}" style="grid-template-columns:minmax(0,1fr) auto"><div><header class="quest-heading"><h3>${copy.title}</h3>${traderIcon("등대지기")}</header><p class="quest-guide">${copy.description}</p><strong>${requirementsLabel}</strong><ul>${requirements.map(text=>`<li>${text}</li>`).join("")}</ul><a class="quest-wiki" href="https://escapefromtarkov.fandom.com/wiki/To_the_Light_-_Trust_but_Verify" target="_blank" rel="noopener noreferrer">${copy.link} ↗</a><section style="margin-top:16px"><strong>${chainLabel}</strong><ol style="margin:8px 0 0;padding-left:22px;line-height:1.7">${questChain.map(step=>`<li>${step.map(([name,slug])=>`<a class="quest-wiki" style="margin-top:4px;font-size:inherit;overflow-wrap:anywhere" href="https://escapefromtarkov.fandom.com/wiki/${encodeURIComponent(slug)}" target="_blank" rel="noopener noreferrer">To the Light - ${name} ↗</a>`).join(" / ")}</li>`).join("")}</ol></section></div><button type="button" class="quest-complete ${completed?"active":""}" style="grid-column:auto" data-lightkeeper-complete aria-pressed="${completed}">${buttonLabel}</button></article>`;
}

function renderQuests(){const u=UI[language],wikiLabel=language==="ko"?"위키에서 자세히":language==="ja"?"Wikiで詳細を見る":"View on Wiki",completeLabel=language==="ko"?"완료":language==="ja"?"完了":"COMPLETE",undoLabel=language==="ko"?"완료 취소":language==="ja"?"完了を取消":"UNDO",doneLabel=language==="ko"?"완료한 퀘스트":language==="ja"?"完了クエスト":"Completed quests",itemLabel=language==="ko"?"필요 아이템":language==="ja"?"必要アイテム":"Required items",subQuestLabel=language==="ko"?"서브":language==="ja"?"サブ":"SIDE";document.querySelector("#quest-app").innerHTML=`<div class="tool-wrap"><header class="tool-hero"><div><small>KORD BREACH · SEASON 1</small><h2>${u.questTitle}</h2><p>${u.questDesc}</p></div><div class="tool-summary"><span class="summary-chip"><small>${doneLabel}</small><b>${questsDone.size} / ${QUESTS.length}</b></span></div></header><div class="quest-list">${QUESTS.map((q,i)=>{const isSubQuest=QUEST_SUBQUESTS.has(i),marker=QUEST_UNNUMBERED.has(i)?"":isSubQuest?subQuestLabel:(questsDone.has(i)?"✓":String(questDisplayNumber(i)).padStart(2,"0")),level=QUEST_LEVELS[i];return `<article class="quest-card ${isSubQuest?"subquest":""} ${questsDone.has(i)?"completed":""}"><span class="quest-no ${isSubQuest?"subquest-label":""}">${marker}</span><div><header class="quest-heading"><h3>${q[0]}</h3>${level?`<span class="quest-level">${level[language]}</span>`:""}${traderIcon(q[1])}<span class="trader">${QUEST_AREAS[i]}</span></header>${q[0]==="Historical Prospects"?renderHistoricalDogtags():""}${QUEST_ITEMS[i].length?`<div class="quest-items" aria-label="${itemLabel}">${QUEST_ITEMS[i].map(item=>`<span class="quest-item" title="${item.name}${item.qty?` ×${item.qty}`:""}"><img src="${item.icon}" alt="${item.name}" width="44" height="44" loading="lazy" decoding="async"></span>`).join("")}</div>`:""}<ul><li>${language==="ko"?q[2]:QUEST_GOALS[language][i]}</li><li class="quest-guide">${QUEST_GUIDES[language][i]}</li></ul>${i===11?renderChoiceRewards():""}${QUEST_WIKI[i]?`<a class="quest-wiki" href="${QUEST_WIKI[i]}" target="_blank" rel="noopener noreferrer">${wikiLabel} ↗</a>`:""}</div><button type="button" class="quest-complete ${questsDone.has(i)?"active":""}" data-quest-complete="${i}" aria-pressed="${questsDone.has(i)}">${questsDone.has(i)?undoLabel:completeLabel}</button></article>${q[0]==="Digital Puzzle"?renderLightkeeperUnlockNotice():""}`}).join("")}</div></div>`}
function entries(){let index=0;return ALLERGY.flatMap(([group,items])=>items.map(([ko,en])=>{const itemId=ALLERGY_ITEM_IDS[index++];return{id:en.toLowerCase().replace(/[^a-z0-9]+/g,"-"),group,ko,en,icon:`https://assets.tarkov.dev/${itemId}-icon.webp`}}))}
function renderAllergy(){
  const u=UI[language],all=entries(),counts=Object.values(allergy).reduce((a,v)=>(v==="allergic"&&a.a++,v==="safe"&&a.s++,a),{a:0,s:0});
  const groups=ALLERGY.map(([group,items],i)=>[group,u.groups[i],items.map(([ko,en])=>all.find(x=>x.en===en)).filter(x=>(filter==="전체"||filter===group)&&`${x.ko} ${x.en}`.toLowerCase().includes(query))]).filter(x=>x[2].length);
  const imageSource=language==="ko"?"아이템 이미지 제공: tarkov.dev":language==="ja"?"アイテム画像提供: tarkov.dev":"Item images provided by tarkov.dev";
  document.querySelector("#allergy-app").innerHTML=`<div class="tool-wrap"><header class="tool-hero"><div><small>ALLERGIC · COST +3</small><h2>${u.allergyTitle}</h2><p>${u.allergyDesc}</p></div><div class="tool-summary"><span class="summary-chip"><small>${u.allergic}</small><b>${counts.a} / 3</b></span><span class="summary-chip"><small>${u.safeChecked}</small><b>${counts.s}</b></span><span class="summary-chip"><small>${u.totalCandidates}</small><b>${all.length}</b></span></div></header><div class="toolbar"><input id="allergy-search" type="search" value="${query}" placeholder="${u.search}"><div>${[["전체",u.all],...ALLERGY.map((x,i)=>[x[0],u.groups[i]])].map(([value,label])=>`<button class="filter-button ${filter===value?"active":""}" data-filter="${value}">${label}</button>`).join("")}</div><button data-reset-allergy>${u.reset}</button></div>${groups.length?groups.map(([g,label,items])=>`<section><header class="section-title"><h3>${label}</h3><span>${items.length}${u.count}</span></header><div class="card-grid">${items.map(x=>`<article class="item-card"><div class="allergy-item-heading"><span class="allergy-item-icon"><img src="${x.icon}" alt="" width="60" height="60" loading="lazy" decoding="async" onerror="this.hidden=true"></span><span><strong>${language==="ko"?x.ko:x.en}</strong>${language==="ko"?`<small>${x.en}</small>`:""}</span></div><div class="item-actions"><button class="allergic ${allergy[x.id]==="allergic"?"active":""}" data-item="${x.id}" data-status="allergic">${u.allergic}</button><button class="safe ${allergy[x.id]==="safe"?"active":""}" data-item="${x.id}" data-status="safe">${u.safe}</button></div></article>`).join("")}</div></section>`).join(""):`<p class="empty-copy">${u.noResults}</p>`}<p class="source-note"><a href="https://tarkov.dev/" target="_blank" rel="noopener noreferrer">${imageSource} ↗</a></p></div>`
}
function points(){return [...POS,...NEG].filter(x=>selected.has(x[0])).reduce((a,x)=>a+x[3],0)}
function conflictFor(id){const pair=EXCLUSIONS.find(([a,b])=>(a===id&&selected.has(b))||(b===id&&selected.has(a)));return pair?pair.find(x=>x!==id):null}
function achievementMet(a){return a.check?a.check():a.ids?a.ids.every(id=>selected.has(id)):a.pool.filter(id=>selected.has(id)).length>=a.need}
function cards(items){const u=UI[language];return items.map(x=>{const conflict=conflictFor(x[0]),blocked=conflict&&!selected.has(x[0]);return `<button class="modifier-card ${selected.has(x[0])?"selected":""} ${blocked?"blocked":""}" data-modifier="${x[0]}" ${blocked?"disabled":""} title="${blocked?u.blocked:""}"><b>${x[3]>0?"+":""}${x[3]}</b><strong>${language==="ko"?x[1]:x[2]}</strong>${language==="ko"?`<small>${x[2]}</small><small>${x[4]}</small>`:""}${blocked?`<small>${u.blocked}</small>`:""}</button>`}).join("")}
function renderModifiers(){
  const u=UI[language],p=points(),chosen=[...NEG,...POS].filter(x=>selected.has(x[0])),achievementTitle=language==="ko"?"달성 가능한 시즌 업적":language==="ja"?"達成可能なシーズン実績":"Available Season Achievements",otherAchievementTitle=language==="ko"?"그외 업적":language==="ja"?"その他の実績":"Other Achievements",otherConditionLabel=language==="ko"?"별도 달성 조건":language==="ja"?"別途達成条件":"SEPARATE REQUIREMENT",metLabel=language==="ko"?"조건 충족":language==="ja"?"条件達成":"READY",complete=language==="ko"?"완료":language==="ja"?"完了":"COMPLETE",undo=language==="ko"?"완료 취소":language==="ja"?"完了を取消":"UNDO";
  const modifierName=id=>{const modifier=[...NEG,...POS].find(x=>x[0]===id);return modifier?(language==="ko"?modifier[1]:modifier[2]):id};
  const achievementCards=(items,group)=>items.map((a,index)=>{const done=(group==="season"?seasonAchievementsDone:otherAchievementsDone).has(index),condition=group==="season"?(achievementMet(a)?metLabel:"SEASON 1"):otherConditionLabel,showRequirements=group==="season"&&(a.name.en==="Genetic Lottery"||a.name.en==="You Call That a Challenge?"),requiredIds=a.ids||a.pool||[],requirementLabel=a.pool?(language==="ko"?`아래 ${requiredIds.length}개 중 ${a.need}개 선택`:language==="ja"?`以下の${requiredIds.length}個から${a.need}個選択`:`Choose ${a.need} of ${requiredIds.length}`):(language==="ko"?"필수 모디파이어":language==="ja"?"必須モディファイア":"Required modifiers"),requirements=showRequirements?`<div class="achievement-requirements"><b>${requirementLabel}</b><div>${requiredIds.map(id=>`<span class="${selected.has(id)?"selected":""}">${modifierName(id)}</span>`).join("")}</div></div>`:"";return `<article class="achievement-card ${done?"met":""}"><div class="achievement-copy"><b>${condition}</b><strong>${a.name[language]}</strong><small>${a.note[language]}</small>${requirements}</div><button type="button" class="achievement-complete ${done?"active":""}" data-achievement-group="${group}" data-achievement-index="${index}" aria-pressed="${done}">${done?undo:complete}</button></article>`}).join("");
  document.querySelector("#modifier-app").innerHTML=`<div class="tool-wrap"><header class="tool-hero"><div><small>PERSONAL MODIFIER</small><h2>${u.modifierTitle}</h2><p>${u.modifierDesc}</p></div><div class="tool-summary"><span class="summary-chip"><small>${u.points}</small><b class="points ${p>=0?"pass":"fail"}">${p>0?"+":""}${p}</b></span><span class="summary-chip"><small>${u.selected}</small><b>${chosen.length} / 33</b></span><span class="summary-chip"><small>${u.result}</small><b class="points ${p>=0?"pass":"fail"}">${p>=0?"PASS":u.shortage}</b></span></div></header><section class="modifier-section global"><header class="section-title"><h3>${u.global}</h3><span>${u.globalNote}</span></header><div class="card-grid global-grid">${GLOBAL.map(g=>`<article class="modifier-card global-card"><b>GLOBAL</b><strong>${g[language][0]}</strong><small>${g[language][1]}</small></article>`).join("")}</div></section><div class="toolbar"><button data-reset-modifier>${u.reset}</button></div><div class="selected-strip">${chosen.length?chosen.map(x=>`<span>${language==="ko"?x[1]:x[2]} ${x[3]>0?"+":""}${x[3]}</span>`).join(""):`<span>${u.none}</span>`}</div><section class="modifier-section negative"><header class="section-title"><h3>${u.negative}</h3><span>14${u.count}</span></header><div class="card-grid">${cards(NEG)}</div></section><section class="modifier-section positive"><header class="section-title"><h3>${u.positive}</h3><span>19${u.count}</span></header><div class="card-grid">${cards(POS)}</div></section><section class="modifier-section achievements"><header class="section-title"><h3>${achievementTitle}</h3><span>${seasonAchievementsDone.size} / ${ACHIEVEMENTS.length}</span></header><div class="achievement-grid">${achievementCards(ACHIEVEMENTS,"season")}</div></section><section class="modifier-section achievements other-achievements"><header class="section-title"><h3>${otherAchievementTitle}</h3><span>${otherAchievementsDone.size} / ${OTHER_SEASON_ACHIEVEMENTS.length}</span></header><div class="achievement-grid">${achievementCards(OTHER_SEASON_ACHIEVEMENTS,"other")}</div></section></div>`
}
function renderKappa(){
  const u=KAPPA_UI[language],conditions=KAPPA_REQUIREMENTS.filter(x=>x.type==="condition"),quests=KAPPA_REQUIREMENTS.filter(x=>x.type==="quest"),questDone=quests.filter(x=>kappaRequirements.has(x.id)).length,itemDone=KAPPA_ITEMS.filter(x=>kappaItems.has(x.id)).length;
  const requirementCards=items=>items.map(x=>`<article class="check-card ${x.portrait?"trader-check":""} ${kappaRequirements.has(x.id)?"checked":""}"><button type="button" data-kappa-kind="requirement" data-kappa-id="${x.id}" aria-pressed="${kappaRequirements.has(x.id)}"><span class="check-mark">${kappaRequirements.has(x.id)?"✓":""}</span>${x.portrait?`<span class="trader-portrait"><img src="${x.portrait}" alt="" width="54" height="54" loading="lazy" decoding="async" onerror="this.hidden=true"></span>`:""}<strong>${x[language]}</strong></button>${x.wiki?`<a href="https://escapefromtarkov.fandom.com/wiki/${x.wiki}" target="_blank" rel="noopener noreferrer">WIKI ↗</a>`:""}</article>`).join("");
  document.querySelector("#kappa-app").innerHTML=`<div class="tool-wrap"><header class="tool-hero"><div><small>FENCE · COLLECTOR</small><h2>${u.title}</h2><p>${u.desc}</p></div><div class="tool-summary"><span class="summary-chip"><small>${u.items}</small><b>${itemDone} / ${KAPPA_ITEMS.length}</b></span><span class="summary-chip"><small>${u.quests}</small><b>${questDone} / ${quests.length}</b></span><span class="summary-chip"><small>${u.remaining}</small><b>${KAPPA_ITEMS.length-itemDone}</b></span></div></header><div class="toolbar kappa-toolbar"><span class="kappa-fir-notice">${u.fir}</span><button data-reset-kappa>${u.reset}</button></div><section class="kappa-section"><header class="section-title"><h3>${u.requirements}</h3><span>${conditions.filter(x=>kappaRequirements.has(x.id)).length} / ${conditions.length}</span></header><div class="check-grid requirements-grid">${requirementCards(conditions)}</div></section><section class="kappa-section"><header class="section-title"><h3>${u.quests}</h3><span>${questDone} / ${quests.length}</span></header><div class="check-grid quest-check-grid">${requirementCards(quests)}</div></section><section class="kappa-section"><header class="section-title"><h3>${u.items}</h3><span>${itemDone} / ${KAPPA_ITEMS.length}</span></header><div class="kappa-progress" aria-label="${u.items} ${itemDone} / ${KAPPA_ITEMS.length}"><i style="width:${itemDone/KAPPA_ITEMS.length*100}%"></i></div><div class="check-grid item-check-grid">${KAPPA_ITEMS.map(x=>`<button type="button" class="check-card item-check ${kappaItems.has(x.id)?"checked":""}" data-kappa-kind="item" data-kappa-id="${x.id}" aria-pressed="${kappaItems.has(x.id)}"><span class="kappa-item-icon"><img src="${x.icon}" alt="" width="52" height="52" loading="lazy" decoding="async" onerror="this.hidden=true"></span><strong>${x.name}</strong><small>${kappaItems.has(x.id)?u.found:u.remaining}</small></button>`).join("")}</div></section><p class="source-note"><a href="https://escapefromtarkov.fandom.com/wiki/Collector" target="_blank" rel="noopener noreferrer">${u.source} ↗</a><span> · </span><a href="https://tarkov.dev/" target="_blank" rel="noopener noreferrer">${u.imageSource} ↗</a></p></div>`
  const heroCopy=document.querySelector("#kappa-app .tool-hero>div:first-child");heroCopy.classList.add("kappa-hero-copy");heroCopy.insertAdjacentHTML("afterbegin",`<span class="fence-hero-portrait"><img src="https://assets.tarkov.dev/579dc571d53a0658a154fbec.webp" alt="Fence" width="86" height="86" decoding="async" onerror="this.hidden=true"></span>`)
}
document.querySelector("#hub-nav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b){e.preventDefault();setView(b.dataset.view)}});
document.querySelector("#hub-map-menu").addEventListener("click",e=>{const map=e.target.closest("[data-hub-map]");if(map)setMap(map.dataset.hubMap)});
document.querySelector("#menu-toggle").addEventListener("click",()=>{document.querySelector("#hub-nav").classList.add("open");document.querySelector("#nav-backdrop").classList.add("open")});
document.querySelector("#nav-backdrop").addEventListener("click",closeMenu);
document.querySelector("#hub-language").addEventListener("change",e=>setLanguage(e.target.value));
document.querySelector("#quest-app").addEventListener("click",e=>{if(e.target.closest("[data-lightkeeper-complete]")){localStorage.setItem("tarkov-hub:lightkeeper-unlocked:v1",JSON.stringify(read("tarkov-hub:lightkeeper-unlocked:v1",false)!==true));renderQuests();return;}const button=e.target.closest("[data-quest-complete]");if(!button)return;const index=Number(button.dataset.questComplete);questsDone.has(index)?questsDone.delete(index):questsDone.add(index);localStorage.setItem(KEYS.questsDone,JSON.stringify([...questsDone]));renderQuests()});
document.querySelector("#allergy-app").addEventListener("click",e=>{const item=e.target.closest("[data-item]"),f=e.target.closest("[data-filter]");if(item){allergy[item.dataset.item]=allergy[item.dataset.item]===item.dataset.status?"":item.dataset.status;localStorage.setItem(KEYS.allergy,JSON.stringify(allergy));renderAllergy()}else if(f){filter=f.dataset.filter;renderAllergy()}else if(e.target.closest("[data-reset-allergy]")&&confirm(UI[language].confirmReset)){allergy={};localStorage.removeItem(KEYS.allergy);renderAllergy()}});
document.querySelector("#allergy-app").addEventListener("input",e=>{if(e.target.id!=="allergy-search")return;query=e.target.value.toLowerCase();renderAllergy();const x=document.querySelector("#allergy-search");x.focus();x.setSelectionRange(x.value.length,x.value.length)});
document.querySelector("#modifier-app").addEventListener("click",e=>{const achievement=e.target.closest("[data-achievement-group]"),card=e.target.closest("[data-modifier]");if(achievement){const isSeason=achievement.dataset.achievementGroup==="season",set=isSeason?seasonAchievementsDone:otherAchievementsDone,key=isSeason?KEYS.seasonAchievementsDone:KEYS.otherAchievementsDone,index=Number(achievement.dataset.achievementIndex);set.has(index)?set.delete(index):set.add(index);localStorage.setItem(key,JSON.stringify([...set]));renderModifiers();return}if(card){selected.has(card.dataset.modifier)?selected.delete(card.dataset.modifier):selected.add(card.dataset.modifier)}else if(e.target.closest("[data-reset-modifier]"))selected.clear();else return;localStorage.setItem(KEYS.modifiers,JSON.stringify([...selected]));renderModifiers()});
document.querySelector("#kappa-app").addEventListener("click",e=>{const card=e.target.closest("[data-kappa-kind]");if(card){const set=card.dataset.kappaKind==="item"?kappaItems:kappaRequirements;set.has(card.dataset.kappaId)?set.delete(card.dataset.kappaId):set.add(card.dataset.kappaId);localStorage.setItem(card.dataset.kappaKind==="item"?KEYS.kappaItems:KEYS.kappaRequirements,JSON.stringify([...set]));renderKappa()}else if(e.target.closest("[data-reset-kappa]")&&confirm(KAPPA_UI[language].confirmReset)){kappaItems.clear();kappaRequirements.clear();localStorage.removeItem(KEYS.kappaItems);localStorage.removeItem(KEYS.kappaRequirements);renderKappa()}});
document.querySelector("#hub-language").value=language;
setLanguage(language);setView(PAGE_VIEW,false);
